### ISSUE TITLE
Fix Grunt Warnings

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-cli#133]
We're using Grunt to clean up the code and fix the inconsistent styling. We're taking this one step of warnings at a time to reduce the likelihood of a regression.

- [x] semicolon warnings - Fixed with #132 
- [x] "defined but never used" - Fixed with #134 
- [x] "{x} is not defined" - Fixed with #137 
- [x] "Expected {x} and instead saw {y}" - Fixed with #138 
- [x] Everything else - Fixed with #149

**Comment by rwaldron** [comment]
Updated checklist

**Comment by johnnyman727** [comment]
Last one was fixed with #149.
